title: James Christopher # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Seasoned product leader and entrepreneur with a passion of building human-centered and data-centric products that can help improve the quality of people's life.
  <br><br>
  If you are looking for someone to help your enterprise take your product/service to market.
  <br><br>
  <a href="https://www.linkedin.com/in/jchrisa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
