title: James Asuncion Christopher # your name (or website title) here 
logo: "/images/logo.png?raw=true" # your photo (or logo) here 
description: > Seasoned product leader and entrepreneur with a passion of building human-centered and data-centric products that can help improve the quality of people's life.   
<br><br>   
If you are looking for someone to help your enterprise take your product/service to market.<br><br>   
<a href="https://www.linkedin.com/in/jchrisa/">My LinkedIn Profile</a>
