title: James Asuncion Christopher 
logo: "/images/logo.png?raw=true"
description:
  Seasoned product leader and entrepreneur with a passion of building human-centered and data-centric products that can help improve the quality of people's life.
  <br><br>
  <a href="https://www.linkedin.com/in/jchrisa/">My LinkedIn Profile</a> 
  
